/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libnative_code/libGameMain/libHomura that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: none.
 * MIT.
 */
#include "imports.h"

extern const char sym___aeabi_d2lz[] __asm__("__aeabi_d2lz");
extern const char sym___aeabi_d2ulz[] __asm__("__aeabi_d2ulz");
extern const char sym___aeabi_dcmpgt[] __asm__("__aeabi_dcmpgt");
extern const char sym___aeabi_dcmplt[] __asm__("__aeabi_dcmplt");
extern const char sym___aeabi_f2d[] __asm__("__aeabi_f2d");
extern const char sym___aeabi_f2lz[] __asm__("__aeabi_f2lz");
extern const char sym___aeabi_f2ulz[] __asm__("__aeabi_f2ulz");
extern const char sym___aeabi_fcmpgt[] __asm__("__aeabi_fcmpgt");
extern const char sym___aeabi_fcmplt[] __asm__("__aeabi_fcmplt");
extern const char sym___aeabi_idiv[] __asm__("__aeabi_idiv");
extern const char sym___aeabi_idivmod[] __asm__("__aeabi_idivmod");
extern const char sym___aeabi_l2d[] __asm__("__aeabi_l2d");
extern const char sym___aeabi_l2f[] __asm__("__aeabi_l2f");
extern const char sym___aeabi_ul2d[] __asm__("__aeabi_ul2d");
extern const char sym___errno[] __asm__("__errno");
extern const char sym_acosf[] __asm__("acosf");
extern const char sym_atan2[] __asm__("atan2");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_atol[] __asm__("atol");
extern const char sym_b_AConfiguration_delete[] __asm__("b_AConfiguration_delete");
extern const char sym_b_AConfiguration_fromAssetManager[] __asm__("b_AConfiguration_fromAssetManager");
extern const char sym_b_AConfiguration_getCountry[] __asm__("b_AConfiguration_getCountry");
extern const char sym_b_AConfiguration_getDensity[] __asm__("b_AConfiguration_getDensity");
extern const char sym_b_AConfiguration_getKeyboard[] __asm__("b_AConfiguration_getKeyboard");
extern const char sym_b_AConfiguration_getKeysHidden[] __asm__("b_AConfiguration_getKeysHidden");
extern const char sym_b_AConfiguration_getLanguage[] __asm__("b_AConfiguration_getLanguage");
extern const char sym_b_AConfiguration_getMcc[] __asm__("b_AConfiguration_getMcc");
extern const char sym_b_AConfiguration_getMnc[] __asm__("b_AConfiguration_getMnc");
extern const char sym_b_AConfiguration_getNavHidden[] __asm__("b_AConfiguration_getNavHidden");
extern const char sym_b_AConfiguration_getNavigation[] __asm__("b_AConfiguration_getNavigation");
extern const char sym_b_AConfiguration_getOrientation[] __asm__("b_AConfiguration_getOrientation");
extern const char sym_b_AConfiguration_getScreenLong[] __asm__("b_AConfiguration_getScreenLong");
extern const char sym_b_AConfiguration_getScreenSize[] __asm__("b_AConfiguration_getScreenSize");
extern const char sym_b_AConfiguration_getSdkVersion[] __asm__("b_AConfiguration_getSdkVersion");
extern const char sym_b_AConfiguration_getTouchscreen[] __asm__("b_AConfiguration_getTouchscreen");
extern const char sym_b_AConfiguration_getUiModeNight[] __asm__("b_AConfiguration_getUiModeNight");
extern const char sym_b_AConfiguration_getUiModeType[] __asm__("b_AConfiguration_getUiModeType");
extern const char sym_b_AConfiguration_new[] __asm__("b_AConfiguration_new");
extern const char sym_b_ALooper_addFd[] __asm__("b_ALooper_addFd");
extern const char sym_b_ALooper_forThread[] __asm__("b_ALooper_forThread");
extern const char sym_b_ALooper_pollOnce[] __asm__("b_ALooper_pollOnce");
extern const char sym_b_ALooper_prepare[] __asm__("b_ALooper_prepare");
extern const char sym_b_ALooper_removeFd[] __asm__("b_ALooper_removeFd");
extern const char sym_b_ANativeWindow_acquire[] __asm__("b_ANativeWindow_acquire");
extern const char sym_b_ANativeWindow_fromSurface[] __asm__("b_ANativeWindow_fromSurface");
extern const char sym_b_ANativeWindow_getHeight[] __asm__("b_ANativeWindow_getHeight");
extern const char sym_b_ANativeWindow_getWidth[] __asm__("b_ANativeWindow_getWidth");
extern const char sym_b_ANativeWindow_release[] __asm__("b_ANativeWindow_release");
extern const char sym_b_ANativeWindow_setBuffersGeometry[] __asm__("b_ANativeWindow_setBuffersGeometry");
extern const char sym_b_AndroidBitmap_getInfo[] __asm__("b_AndroidBitmap_getInfo");
extern const char sym_b_AndroidBitmap_lockPixels[] __asm__("b_AndroidBitmap_lockPixels");
extern const char sym_b_AndroidBitmap_unlockPixels[] __asm__("b_AndroidBitmap_unlockPixels");
extern const char sym_b_SL_IID_ANDROIDSIMPLEBUFFERQUEUE[] __asm__("b_SL_IID_ANDROIDSIMPLEBUFFERQUEUE");
extern const char sym_b_SL_IID_ENGINE[] __asm__("b_SL_IID_ENGINE");
extern const char sym_b_SL_IID_PLAY[] __asm__("b_SL_IID_PLAY");
extern const char sym_b___FD_ISSET_chk[] __asm__("b___FD_ISSET_chk");
extern const char sym_b___FD_SET_chk[] __asm__("b___FD_SET_chk");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___assert2[] __asm__("b___assert2");
extern const char sym_b___ctype_get_mb_cur_max[] __asm__("b___ctype_get_mb_cur_max");
extern const char sym_b___cxa_atexit[] __asm__("b___cxa_atexit");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___memcpy_chk[] __asm__("b___memcpy_chk");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b___strncpy_chk2[] __asm__("b___strncpy_chk2");
extern const char sym_b___system_property_get[] __asm__("b___system_property_get");
extern const char sym_b___vsnprintf_chk[] __asm__("b___vsnprintf_chk");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b__exit[] __asm__("b__exit");
extern const char sym_b__tolower_tab_[] __asm__("b__tolower_tab_");
extern const char sym_b__toupper_tab_[] __asm__("b__toupper_tab_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_accept[] __asm__("b_accept");
extern const char sym_b_access[] __asm__("b_access");
extern const char sym_b_android_set_abort_message[] __asm__("b_android_set_abort_message");
extern const char sym_b_asctime[] __asm__("b_asctime");
extern const char sym_b_basename[] __asm__("b_basename");
extern const char sym_b_bind[] __asm__("b_bind");
extern const char sym_b_bsd_signal[] __asm__("b_bsd_signal");
extern const char sym_b_btowc[] __asm__("b_btowc");
extern const char sym_b_ceil[] __asm__("b_ceil");
extern const char sym_b_ceilf[] __asm__("b_ceilf");
extern const char sym_b_chdir[] __asm__("b_chdir");
extern const char sym_b_clock[] __asm__("b_clock");
extern const char sym_b_clock_gettime[] __asm__("b_clock_gettime");
extern const char sym_b_close[] __asm__("b_close");
extern const char sym_b_closedir[] __asm__("b_closedir");
extern const char sym_b_closelog[] __asm__("b_closelog");
extern const char sym_b_compress[] __asm__("b_compress");
extern const char sym_b_connect[] __asm__("b_connect");
extern const char sym_b_crc32[] __asm__("b_crc32");
extern const char sym_b_deflate[] __asm__("b_deflate");
extern const char sym_b_deflateEnd[] __asm__("b_deflateEnd");
extern const char sym_b_deflateInit2_[] __asm__("b_deflateInit2_");
extern const char sym_b_deflateReset[] __asm__("b_deflateReset");
extern const char sym_b_difftime[] __asm__("b_difftime");
extern const char sym_b_dl_unwind_find_exidx[] __asm__("b_dl_unwind_find_exidx");
extern const char sym_b_dlclose[] __asm__("b_dlclose");
extern const char sym_b_dlerror[] __asm__("b_dlerror");
extern const char sym_b_dlopen[] __asm__("b_dlopen");
extern const char sym_b_dlsym[] __asm__("b_dlsym");
extern const char sym_b_eglChooseConfig[] __asm__("b_eglChooseConfig");
extern const char sym_b_eglCreateContext[] __asm__("b_eglCreateContext");
extern const char sym_b_eglCreateWindowSurface[] __asm__("b_eglCreateWindowSurface");
extern const char sym_b_eglDestroyContext[] __asm__("b_eglDestroyContext");
extern const char sym_b_eglDestroySurface[] __asm__("b_eglDestroySurface");
extern const char sym_b_eglGetConfigAttrib[] __asm__("b_eglGetConfigAttrib");
extern const char sym_b_eglGetCurrentContext[] __asm__("b_eglGetCurrentContext");
extern const char sym_b_eglGetCurrentDisplay[] __asm__("b_eglGetCurrentDisplay");
extern const char sym_b_eglGetDisplay[] __asm__("b_eglGetDisplay");
extern const char sym_b_eglGetError[] __asm__("b_eglGetError");
extern const char sym_b_eglGetProcAddress[] __asm__("b_eglGetProcAddress");
extern const char sym_b_eglInitialize[] __asm__("b_eglInitialize");
extern const char sym_b_eglMakeCurrent[] __asm__("b_eglMakeCurrent");
extern const char sym_b_eglQueryContext[] __asm__("b_eglQueryContext");
extern const char sym_b_eglQuerySurface[] __asm__("b_eglQuerySurface");
extern const char sym_b_eglSwapBuffers[] __asm__("b_eglSwapBuffers");
extern const char sym_b_eglTerminate[] __asm__("b_eglTerminate");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fchmod[] __asm__("b_fchmod");
extern const char sym_b_fchmodat[] __asm__("b_fchmodat");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fcntl[] __asm__("b_fcntl");
extern const char sym_b_fdopen[] __asm__("b_fdopen");
extern const char sym_b_fdopendir[] __asm__("b_fdopendir");
extern const char sym_b_feof[] __asm__("b_feof");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_fgetc[] __asm__("b_fgetc");
extern const char sym_b_fgets[] __asm__("b_fgets");
extern const char sym_b_fgetws[] __asm__("b_fgetws");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_floorf[] __asm__("b_floorf");
extern const char sym_b_fminf[] __asm__("b_fminf");
extern const char sym_b_fnmatch[] __asm__("b_fnmatch");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_freelocale[] __asm__("b_freelocale");
extern const char sym_b_fscanf[] __asm__("b_fscanf");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_fseeko[] __asm__("b_fseeko");
extern const char sym_b_fstat[] __asm__("b_fstat");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_ftello[] __asm__("b_ftello");
extern const char sym_b_ftime[] __asm__("b_ftime");
extern const char sym_b_ftruncate[] __asm__("b_ftruncate");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_getc[] __asm__("b_getc");
extern const char sym_b_getcwd[] __asm__("b_getcwd");
extern const char sym_b_getenv[] __asm__("b_getenv");
extern const char sym_b_geteuid[] __asm__("b_geteuid");
extern const char sym_b_gethostbyname[] __asm__("b_gethostbyname");
extern const char sym_b_gethostname[] __asm__("b_gethostname");
extern const char sym_b_getpagesize[] __asm__("b_getpagesize");
extern const char sym_b_getpeername[] __asm__("b_getpeername");
extern const char sym_b_getpid[] __asm__("b_getpid");
extern const char sym_b_getpwuid[] __asm__("b_getpwuid");
extern const char sym_b_getrlimit[] __asm__("b_getrlimit");
extern const char sym_b_getrusage[] __asm__("b_getrusage");
extern const char sym_b_getservbyname[] __asm__("b_getservbyname");
extern const char sym_b_getsockname[] __asm__("b_getsockname");
extern const char sym_b_getsockopt[] __asm__("b_getsockopt");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_getwc[] __asm__("b_getwc");
extern const char sym_b_gmtime[] __asm__("b_gmtime");
extern const char sym_b_gmtime_r[] __asm__("b_gmtime_r");
extern const char sym_b_inet_addr[] __asm__("b_inet_addr");
extern const char sym_b_inet_ntoa[] __asm__("b_inet_ntoa");
extern const char sym_b_inet_ntop[] __asm__("b_inet_ntop");
extern const char sym_b_inet_pton[] __asm__("b_inet_pton");
extern const char sym_b_inflate[] __asm__("b_inflate");
extern const char sym_b_inflateEnd[] __asm__("b_inflateEnd");
extern const char sym_b_inflateInit2_[] __asm__("b_inflateInit2_");
extern const char sym_b_inflateInit_[] __asm__("b_inflateInit_");
extern const char sym_b_inflateReset[] __asm__("b_inflateReset");
extern const char sym_b_ioctl[] __asm__("b_ioctl");
extern const char sym_b_iswalpha_l[] __asm__("b_iswalpha_l");
extern const char sym_b_iswblank_l[] __asm__("b_iswblank_l");
extern const char sym_b_iswcntrl_l[] __asm__("b_iswcntrl_l");
extern const char sym_b_iswdigit_l[] __asm__("b_iswdigit_l");
extern const char sym_b_iswlower_l[] __asm__("b_iswlower_l");
extern const char sym_b_iswprint_l[] __asm__("b_iswprint_l");
extern const char sym_b_iswpunct_l[] __asm__("b_iswpunct_l");
extern const char sym_b_iswspace_l[] __asm__("b_iswspace_l");
extern const char sym_b_iswupper_l[] __asm__("b_iswupper_l");
extern const char sym_b_iswxdigit_l[] __asm__("b_iswxdigit_l");
extern const char sym_b_kill[] __asm__("b_kill");
extern const char sym_b_link[] __asm__("b_link");
extern const char sym_b_listen[] __asm__("b_listen");
extern const char sym_b_localeconv[] __asm__("b_localeconv");
extern const char sym_b_localtime[] __asm__("b_localtime");
extern const char sym_b_localtime_r[] __asm__("b_localtime_r");
extern const char sym_b_longjmp[] __asm__("b_longjmp");
extern const char sym_b_lroundf[] __asm__("b_lroundf");
extern const char sym_b_lseek[] __asm__("b_lseek");
extern const char sym_b_lstat[] __asm__("b_lstat");
extern const char sym_b_mbrlen[] __asm__("b_mbrlen");
extern const char sym_b_mbrtowc[] __asm__("b_mbrtowc");
extern const char sym_b_mbsnrtowcs[] __asm__("b_mbsnrtowcs");
extern const char sym_b_mbsrtowcs[] __asm__("b_mbsrtowcs");
extern const char sym_b_mbtowc[] __asm__("b_mbtowc");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_mkdir[] __asm__("b_mkdir");
extern const char sym_b_mknod[] __asm__("b_mknod");
extern const char sym_b_mmap[] __asm__("b_mmap");
extern const char sym_b_modf[] __asm__("b_modf");
extern const char sym_b_mprotect[] __asm__("b_mprotect");
extern const char sym_b_munmap[] __asm__("b_munmap");
extern const char sym_b_nanosleep[] __asm__("b_nanosleep");
extern const char sym_b_newlocale[] __asm__("b_newlocale");
extern const char sym_b_open[] __asm__("b_open");
extern const char sym_b_openat[] __asm__("b_openat");
extern const char sym_b_opendir[] __asm__("b_opendir");
extern const char sym_b_openlog[] __asm__("b_openlog");
extern const char sym_b_pathconf[] __asm__("b_pathconf");
extern const char sym_b_perror[] __asm__("b_perror");
extern const char sym_b_pipe[] __asm__("b_pipe");
extern const char sym_b_poll[] __asm__("b_poll");
extern const char sym_b_posix_memalign[] __asm__("b_posix_memalign");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_pthread_attr_destroy[] __asm__("b_pthread_attr_destroy");
extern const char sym_b_pthread_attr_getschedparam[] __asm__("b_pthread_attr_getschedparam");
extern const char sym_b_pthread_attr_getschedpolicy[] __asm__("b_pthread_attr_getschedpolicy");
extern const char sym_b_pthread_attr_getstacksize[] __asm__("b_pthread_attr_getstacksize");
extern const char sym_b_pthread_attr_init[] __asm__("b_pthread_attr_init");
extern const char sym_b_pthread_attr_setdetachstate[] __asm__("b_pthread_attr_setdetachstate");
extern const char sym_b_pthread_attr_setschedparam[] __asm__("b_pthread_attr_setschedparam");
extern const char sym_b_pthread_attr_setstacksize[] __asm__("b_pthread_attr_setstacksize");
extern const char sym_b_pthread_cond_broadcast[] __asm__("b_pthread_cond_broadcast");
extern const char sym_b_pthread_cond_destroy[] __asm__("b_pthread_cond_destroy");
extern const char sym_b_pthread_cond_init[] __asm__("b_pthread_cond_init");
extern const char sym_b_pthread_cond_signal[] __asm__("b_pthread_cond_signal");
extern const char sym_b_pthread_cond_timedwait[] __asm__("b_pthread_cond_timedwait");
extern const char sym_b_pthread_cond_wait[] __asm__("b_pthread_cond_wait");
extern const char sym_b_pthread_create[] __asm__("b_pthread_create");
extern const char sym_b_pthread_detach[] __asm__("b_pthread_detach");
extern const char sym_b_pthread_equal[] __asm__("b_pthread_equal");
extern const char sym_b_pthread_exit[] __asm__("b_pthread_exit");
extern const char sym_b_pthread_getspecific[] __asm__("b_pthread_getspecific");
extern const char sym_b_pthread_join[] __asm__("b_pthread_join");
extern const char sym_b_pthread_key_create[] __asm__("b_pthread_key_create");
extern const char sym_b_pthread_key_delete[] __asm__("b_pthread_key_delete");
extern const char sym_b_pthread_mutex_destroy[] __asm__("b_pthread_mutex_destroy");
extern const char sym_b_pthread_mutex_init[] __asm__("b_pthread_mutex_init");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_trylock[] __asm__("b_pthread_mutex_trylock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_pthread_mutexattr_destroy[] __asm__("b_pthread_mutexattr_destroy");
extern const char sym_b_pthread_mutexattr_init[] __asm__("b_pthread_mutexattr_init");
extern const char sym_b_pthread_mutexattr_settype[] __asm__("b_pthread_mutexattr_settype");
extern const char sym_b_pthread_once[] __asm__("b_pthread_once");
extern const char sym_b_pthread_self[] __asm__("b_pthread_self");
extern const char sym_b_pthread_setspecific[] __asm__("b_pthread_setspecific");
extern const char sym_b_putc[] __asm__("b_putc");
extern const char sym_b_putenv[] __asm__("b_putenv");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_putwc[] __asm__("b_putwc");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_read[] __asm__("b_read");
extern const char sym_b_readdir[] __asm__("b_readdir");
extern const char sym_b_readlink[] __asm__("b_readlink");
extern const char sym_b_realpath[] __asm__("b_realpath");
extern const char sym_b_recv[] __asm__("b_recv");
extern const char sym_b_recvfrom[] __asm__("b_recvfrom");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_rename[] __asm__("b_rename");
extern const char sym_b_rmdir[] __asm__("b_rmdir");
extern const char sym_b_roundf[] __asm__("b_roundf");
extern const char sym_b_sched_get_priority_max[] __asm__("b_sched_get_priority_max");
extern const char sym_b_sched_get_priority_min[] __asm__("b_sched_get_priority_min");
extern const char sym_b_sched_yield[] __asm__("b_sched_yield");
extern const char sym_b_select[] __asm__("b_select");
extern const char sym_b_send[] __asm__("b_send");
extern const char sym_b_sendfile[] __asm__("b_sendfile");
extern const char sym_b_sendto[] __asm__("b_sendto");
extern const char sym_b_setbuf[] __asm__("b_setbuf");
extern const char sym_b_setenv[] __asm__("b_setenv");
extern const char sym_b_setjmp[] __asm__("b_setjmp");
extern const char sym_b_setlocale[] __asm__("b_setlocale");
extern const char sym_b_setrlimit[] __asm__("b_setrlimit");
extern const char sym_b_setsockopt[] __asm__("b_setsockopt");
extern const char sym_b_setvbuf[] __asm__("b_setvbuf");
extern const char sym_b_shutdown[] __asm__("b_shutdown");
extern const char sym_b_sigaction[] __asm__("b_sigaction");
extern const char sym_b_sigemptyset[] __asm__("b_sigemptyset");
extern const char sym_b_sincos[] __asm__("b_sincos");
extern const char sym_b_sincosf[] __asm__("b_sincosf");
extern const char sym_b_slCreateEngine[] __asm__("b_slCreateEngine");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_socket[] __asm__("b_socket");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_stat[] __asm__("b_stat");
extern const char sym_b_statvfs[] __asm__("b_statvfs");
extern const char sym_b_strcoll_l[] __asm__("b_strcoll_l");
extern const char sym_b_strerror[] __asm__("b_strerror");
extern const char sym_b_strerror_r[] __asm__("b_strerror_r");
extern const char sym_b_strftime[] __asm__("b_strftime");
extern const char sym_b_strftime_l[] __asm__("b_strftime_l");
extern const char sym_b_strtold_l[] __asm__("b_strtold_l");
extern const char sym_b_strtoll_l[] __asm__("b_strtoll_l");
extern const char sym_b_strtoull_l[] __asm__("b_strtoull_l");
extern const char sym_b_strxfrm_l[] __asm__("b_strxfrm_l");
extern const char sym_b_symlink[] __asm__("b_symlink");
extern const char sym_b_syscall[] __asm__("b_syscall");
extern const char sym_b_sysconf[] __asm__("b_sysconf");
extern const char sym_b_syslog[] __asm__("b_syslog");
extern const char sym_b_time[] __asm__("b_time");
extern const char sym_b_towlower_l[] __asm__("b_towlower_l");
extern const char sym_b_towupper_l[] __asm__("b_towupper_l");
extern const char sym_b_truncate[] __asm__("b_truncate");
extern const char sym_b_uncompress[] __asm__("b_uncompress");
extern const char sym_b_ungetc[] __asm__("b_ungetc");
extern const char sym_b_ungetwc[] __asm__("b_ungetwc");
extern const char sym_b_unlink[] __asm__("b_unlink");
extern const char sym_b_unlinkat[] __asm__("b_unlinkat");
extern const char sym_b_uselocale[] __asm__("b_uselocale");
extern const char sym_b_utimensat[] __asm__("b_utimensat");
extern const char sym_b_vasprintf[] __asm__("b_vasprintf");
extern const char sym_b_vfprintf[] __asm__("b_vfprintf");
extern const char sym_b_vsnprintf[] __asm__("b_vsnprintf");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_b_wcrtomb[] __asm__("b_wcrtomb");
extern const char sym_b_wcscoll_l[] __asm__("b_wcscoll_l");
extern const char sym_b_wcsftime[] __asm__("b_wcsftime");
extern const char sym_b_wcsnrtombs[] __asm__("b_wcsnrtombs");
extern const char sym_b_wcsrtombs[] __asm__("b_wcsrtombs");
extern const char sym_b_wcsxfrm_l[] __asm__("b_wcsxfrm_l");
extern const char sym_b_wctob[] __asm__("b_wctob");
extern const char sym_b_write[] __asm__("b_write");
extern const char sym_b_writev[] __asm__("b_writev");
extern const char sym_b_zError[] __asm__("b_zError");
extern const char sym_bsearch[] __asm__("bsearch");
extern const char sym_calloc[] __asm__("calloc");
extern const char sym_cos[] __asm__("cos");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_exp[] __asm__("exp");
extern const char sym_free[] __asm__("free");
extern const char sym_frexp[] __asm__("frexp");
extern const char sym_iswctype[] __asm__("iswctype");
extern const char sym_log[] __asm__("log");
extern const char sym_log10[] __asm__("log10");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_lrintf[] __asm__("lrintf");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memalign[] __asm__("memalign");
extern const char sym_memchr[] __asm__("memchr");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_qsort[] __asm__("qsort");
extern const char sym_realloc[] __asm__("realloc");
extern const char sym_sin[] __asm__("sin");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcasecmp[] __asm__("strcasecmp");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcoll[] __asm__("strcoll");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strcspn[] __asm__("strcspn");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncasecmp[] __asm__("strncasecmp");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strncpy[] __asm__("strncpy");
extern const char sym_strnlen[] __asm__("strnlen");
extern const char sym_strpbrk[] __asm__("strpbrk");
extern const char sym_strrchr[] __asm__("strrchr");
extern const char sym_strspn[] __asm__("strspn");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strtof[] __asm__("strtof");
extern const char sym_strtok[] __asm__("strtok");
extern const char sym_strtok_r[] __asm__("strtok_r");
extern const char sym_strtol[] __asm__("strtol");
extern const char sym_strtold[] __asm__("strtold");
extern const char sym_strtoll[] __asm__("strtoll");
extern const char sym_strtoul[] __asm__("strtoul");
extern const char sym_strtoull[] __asm__("strtoull");
extern const char sym_strxfrm[] __asm__("strxfrm");
extern const char sym_swprintf[] __asm__("swprintf");
extern const char sym_tan[] __asm__("tan");
extern const char sym_towlower[] __asm__("towlower");
extern const char sym_towupper[] __asm__("towupper");
extern const char sym_vsscanf[] __asm__("vsscanf");
extern const char sym_wcscoll[] __asm__("wcscoll");
extern const char sym_wcslen[] __asm__("wcslen");
extern const char sym_wcstod[] __asm__("wcstod");
extern const char sym_wcstof[] __asm__("wcstof");
extern const char sym_wcstol[] __asm__("wcstol");
extern const char sym_wcstold[] __asm__("wcstold");
extern const char sym_wcstoll[] __asm__("wcstoll");
extern const char sym_wcstoul[] __asm__("wcstoul");
extern const char sym_wcstoull[] __asm__("wcstoull");
extern const char sym_wcsxfrm[] __asm__("wcsxfrm");
extern const char sym_wctype[] __asm__("wctype");
extern const char sym_wmemchr[] __asm__("wmemchr");
extern const char sym_wmemcmp[] __asm__("wmemcmp");
extern const char sym_wmemcpy[] __asm__("wmemcpy");
extern const char sym_wmemmove[] __asm__("wmemmove");
extern const char sym_wmemset[] __asm__("wmemset");

DynLibFunction dcr_imports[] = {
    {"AConfiguration_delete", (uintptr_t)sym_b_AConfiguration_delete},
    {"AConfiguration_fromAssetManager", (uintptr_t)sym_b_AConfiguration_fromAssetManager},
    {"AConfiguration_getCountry", (uintptr_t)sym_b_AConfiguration_getCountry},
    {"AConfiguration_getDensity", (uintptr_t)sym_b_AConfiguration_getDensity},
    {"AConfiguration_getKeyboard", (uintptr_t)sym_b_AConfiguration_getKeyboard},
    {"AConfiguration_getKeysHidden", (uintptr_t)sym_b_AConfiguration_getKeysHidden},
    {"AConfiguration_getLanguage", (uintptr_t)sym_b_AConfiguration_getLanguage},
    {"AConfiguration_getMcc", (uintptr_t)sym_b_AConfiguration_getMcc},
    {"AConfiguration_getMnc", (uintptr_t)sym_b_AConfiguration_getMnc},
    {"AConfiguration_getNavHidden", (uintptr_t)sym_b_AConfiguration_getNavHidden},
    {"AConfiguration_getNavigation", (uintptr_t)sym_b_AConfiguration_getNavigation},
    {"AConfiguration_getOrientation", (uintptr_t)sym_b_AConfiguration_getOrientation},
    {"AConfiguration_getScreenLong", (uintptr_t)sym_b_AConfiguration_getScreenLong},
    {"AConfiguration_getScreenSize", (uintptr_t)sym_b_AConfiguration_getScreenSize},
    {"AConfiguration_getSdkVersion", (uintptr_t)sym_b_AConfiguration_getSdkVersion},
    {"AConfiguration_getTouchscreen", (uintptr_t)sym_b_AConfiguration_getTouchscreen},
    {"AConfiguration_getUiModeNight", (uintptr_t)sym_b_AConfiguration_getUiModeNight},
    {"AConfiguration_getUiModeType", (uintptr_t)sym_b_AConfiguration_getUiModeType},
    {"AConfiguration_new", (uintptr_t)sym_b_AConfiguration_new},
    {"ALooper_addFd", (uintptr_t)sym_b_ALooper_addFd},
    {"ALooper_forThread", (uintptr_t)sym_b_ALooper_forThread},
    {"ALooper_pollOnce", (uintptr_t)sym_b_ALooper_pollOnce},
    {"ALooper_prepare", (uintptr_t)sym_b_ALooper_prepare},
    {"ALooper_removeFd", (uintptr_t)sym_b_ALooper_removeFd},
    {"ANativeWindow_acquire", (uintptr_t)sym_b_ANativeWindow_acquire},
    {"ANativeWindow_fromSurface", (uintptr_t)sym_b_ANativeWindow_fromSurface},
    {"ANativeWindow_getHeight", (uintptr_t)sym_b_ANativeWindow_getHeight},
    {"ANativeWindow_getWidth", (uintptr_t)sym_b_ANativeWindow_getWidth},
    {"ANativeWindow_release", (uintptr_t)sym_b_ANativeWindow_release},
    {"ANativeWindow_setBuffersGeometry", (uintptr_t)sym_b_ANativeWindow_setBuffersGeometry},
    {"AndroidBitmap_getInfo", (uintptr_t)sym_b_AndroidBitmap_getInfo},
    {"AndroidBitmap_lockPixels", (uintptr_t)sym_b_AndroidBitmap_lockPixels},
    {"AndroidBitmap_unlockPixels", (uintptr_t)sym_b_AndroidBitmap_unlockPixels},
    {"SL_IID_ANDROIDSIMPLEBUFFERQUEUE", (uintptr_t)sym_b_SL_IID_ANDROIDSIMPLEBUFFERQUEUE},
    {"SL_IID_ENGINE", (uintptr_t)sym_b_SL_IID_ENGINE},
    {"SL_IID_PLAY", (uintptr_t)sym_b_SL_IID_PLAY},
    {"__FD_ISSET_chk", (uintptr_t)sym_b___FD_ISSET_chk},
    {"__FD_SET_chk", (uintptr_t)sym_b___FD_SET_chk},
    {"__aeabi_d2lz", (uintptr_t)sym___aeabi_d2lz},
    {"__aeabi_d2ulz", (uintptr_t)sym___aeabi_d2ulz},
    {"__aeabi_dcmpgt", (uintptr_t)sym___aeabi_dcmpgt},
    {"__aeabi_dcmplt", (uintptr_t)sym___aeabi_dcmplt},
    {"__aeabi_f2d", (uintptr_t)sym___aeabi_f2d},
    {"__aeabi_f2lz", (uintptr_t)sym___aeabi_f2lz},
    {"__aeabi_f2ulz", (uintptr_t)sym___aeabi_f2ulz},
    {"__aeabi_fcmpgt", (uintptr_t)sym___aeabi_fcmpgt},
    {"__aeabi_fcmplt", (uintptr_t)sym___aeabi_fcmplt},
    {"__aeabi_idiv", (uintptr_t)sym___aeabi_idiv},
    {"__aeabi_idivmod", (uintptr_t)sym___aeabi_idivmod},
    {"__aeabi_l2d", (uintptr_t)sym___aeabi_l2d},
    {"__aeabi_l2f", (uintptr_t)sym___aeabi_l2f},
    {"__aeabi_ul2d", (uintptr_t)sym___aeabi_ul2d},
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__assert2", (uintptr_t)sym_b___assert2},
    {"__ctype_get_mb_cur_max", (uintptr_t)sym_b___ctype_get_mb_cur_max},
    {"__cxa_atexit", (uintptr_t)sym_b___cxa_atexit},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__errno", (uintptr_t)sym___errno},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__memcpy_chk", (uintptr_t)sym_b___memcpy_chk},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"__strncpy_chk2", (uintptr_t)sym_b___strncpy_chk2},
    {"__system_property_get", (uintptr_t)sym_b___system_property_get},
    {"__vsnprintf_chk", (uintptr_t)sym_b___vsnprintf_chk},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"_exit", (uintptr_t)sym_b__exit},
    {"_tolower_tab_", (uintptr_t)sym_b__tolower_tab_},
    {"_toupper_tab_", (uintptr_t)sym_b__toupper_tab_},
    {"abort", (uintptr_t)sym_b_abort},
    {"accept", (uintptr_t)sym_b_accept},
    {"access", (uintptr_t)sym_b_access},
    {"acosf", (uintptr_t)sym_acosf},
    {"android_set_abort_message", (uintptr_t)sym_b_android_set_abort_message},
    {"asctime", (uintptr_t)sym_b_asctime},
    {"atan2", (uintptr_t)sym_atan2},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atoi", (uintptr_t)sym_atoi},
    {"atol", (uintptr_t)sym_atol},
    {"basename", (uintptr_t)sym_b_basename},
    {"bind", (uintptr_t)sym_b_bind},
    {"bsd_signal", (uintptr_t)sym_b_bsd_signal},
    {"bsearch", (uintptr_t)sym_bsearch},
    {"btowc", (uintptr_t)sym_b_btowc},
    {"calloc", (uintptr_t)sym_calloc},
    {"ceil", (uintptr_t)sym_b_ceil},
    {"ceilf", (uintptr_t)sym_b_ceilf},
    {"chdir", (uintptr_t)sym_b_chdir},
    {"clock", (uintptr_t)sym_b_clock},
    {"clock_gettime", (uintptr_t)sym_b_clock_gettime},
    {"close", (uintptr_t)sym_b_close},
    {"closedir", (uintptr_t)sym_b_closedir},
    {"closelog", (uintptr_t)sym_b_closelog},
    {"compress", (uintptr_t)sym_b_compress},
    {"connect", (uintptr_t)sym_b_connect},
    {"cos", (uintptr_t)sym_cos},
    {"cosf", (uintptr_t)sym_cosf},
    {"crc32", (uintptr_t)sym_b_crc32},
    {"deflate", (uintptr_t)sym_b_deflate},
    {"deflateEnd", (uintptr_t)sym_b_deflateEnd},
    {"deflateInit2_", (uintptr_t)sym_b_deflateInit2_},
    {"deflateReset", (uintptr_t)sym_b_deflateReset},
    {"difftime", (uintptr_t)sym_b_difftime},
    {"dl_unwind_find_exidx", (uintptr_t)sym_b_dl_unwind_find_exidx},
    {"dlclose", (uintptr_t)sym_b_dlclose},
    {"dlerror", (uintptr_t)sym_b_dlerror},
    {"dlopen", (uintptr_t)sym_b_dlopen},
    {"dlsym", (uintptr_t)sym_b_dlsym},
    {"eglChooseConfig", (uintptr_t)sym_b_eglChooseConfig},
    {"eglCreateContext", (uintptr_t)sym_b_eglCreateContext},
    {"eglCreateWindowSurface", (uintptr_t)sym_b_eglCreateWindowSurface},
    {"eglDestroyContext", (uintptr_t)sym_b_eglDestroyContext},
    {"eglDestroySurface", (uintptr_t)sym_b_eglDestroySurface},
    {"eglGetConfigAttrib", (uintptr_t)sym_b_eglGetConfigAttrib},
    {"eglGetCurrentContext", (uintptr_t)sym_b_eglGetCurrentContext},
    {"eglGetCurrentDisplay", (uintptr_t)sym_b_eglGetCurrentDisplay},
    {"eglGetDisplay", (uintptr_t)sym_b_eglGetDisplay},
    {"eglGetError", (uintptr_t)sym_b_eglGetError},
    {"eglGetProcAddress", (uintptr_t)sym_b_eglGetProcAddress},
    {"eglInitialize", (uintptr_t)sym_b_eglInitialize},
    {"eglMakeCurrent", (uintptr_t)sym_b_eglMakeCurrent},
    {"eglQueryContext", (uintptr_t)sym_b_eglQueryContext},
    {"eglQuerySurface", (uintptr_t)sym_b_eglQuerySurface},
    {"eglSwapBuffers", (uintptr_t)sym_b_eglSwapBuffers},
    {"eglTerminate", (uintptr_t)sym_b_eglTerminate},
    {"exit", (uintptr_t)sym_b_exit},
    {"exp", (uintptr_t)sym_exp},
    {"fchmod", (uintptr_t)sym_b_fchmod},
    {"fchmodat", (uintptr_t)sym_b_fchmodat},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fcntl", (uintptr_t)sym_b_fcntl},
    {"fdopen", (uintptr_t)sym_b_fdopen},
    {"fdopendir", (uintptr_t)sym_b_fdopendir},
    {"feof", (uintptr_t)sym_b_feof},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"fgetc", (uintptr_t)sym_b_fgetc},
    {"fgets", (uintptr_t)sym_b_fgets},
    {"fgetws", (uintptr_t)sym_b_fgetws},
    {"floor", (uintptr_t)sym_b_floor},
    {"floorf", (uintptr_t)sym_b_floorf},
    {"fminf", (uintptr_t)sym_b_fminf},
    {"fnmatch", (uintptr_t)sym_b_fnmatch},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"freelocale", (uintptr_t)sym_b_freelocale},
    {"frexp", (uintptr_t)sym_frexp},
    {"fscanf", (uintptr_t)sym_b_fscanf},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"fseeko", (uintptr_t)sym_b_fseeko},
    {"fstat", (uintptr_t)sym_b_fstat},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"ftello", (uintptr_t)sym_b_ftello},
    {"ftime", (uintptr_t)sym_b_ftime},
    {"ftruncate", (uintptr_t)sym_b_ftruncate},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"getc", (uintptr_t)sym_b_getc},
    {"getcwd", (uintptr_t)sym_b_getcwd},
    {"getenv", (uintptr_t)sym_b_getenv},
    {"geteuid", (uintptr_t)sym_b_geteuid},
    {"gethostbyname", (uintptr_t)sym_b_gethostbyname},
    {"gethostname", (uintptr_t)sym_b_gethostname},
    {"getpagesize", (uintptr_t)sym_b_getpagesize},
    {"getpeername", (uintptr_t)sym_b_getpeername},
    {"getpid", (uintptr_t)sym_b_getpid},
    {"getpwuid", (uintptr_t)sym_b_getpwuid},
    {"getrlimit", (uintptr_t)sym_b_getrlimit},
    {"getrusage", (uintptr_t)sym_b_getrusage},
    {"getservbyname", (uintptr_t)sym_b_getservbyname},
    {"getsockname", (uintptr_t)sym_b_getsockname},
    {"getsockopt", (uintptr_t)sym_b_getsockopt},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"getwc", (uintptr_t)sym_b_getwc},
    {"gmtime", (uintptr_t)sym_b_gmtime},
    {"gmtime_r", (uintptr_t)sym_b_gmtime_r},
    {"inet_addr", (uintptr_t)sym_b_inet_addr},
    {"inet_ntoa", (uintptr_t)sym_b_inet_ntoa},
    {"inet_ntop", (uintptr_t)sym_b_inet_ntop},
    {"inet_pton", (uintptr_t)sym_b_inet_pton},
    {"inflate", (uintptr_t)sym_b_inflate},
    {"inflateEnd", (uintptr_t)sym_b_inflateEnd},
    {"inflateInit2_", (uintptr_t)sym_b_inflateInit2_},
    {"inflateInit_", (uintptr_t)sym_b_inflateInit_},
    {"inflateReset", (uintptr_t)sym_b_inflateReset},
    {"ioctl", (uintptr_t)sym_b_ioctl},
    {"iswalpha_l", (uintptr_t)sym_b_iswalpha_l},
    {"iswblank_l", (uintptr_t)sym_b_iswblank_l},
    {"iswcntrl_l", (uintptr_t)sym_b_iswcntrl_l},
    {"iswctype", (uintptr_t)sym_iswctype},
    {"iswdigit_l", (uintptr_t)sym_b_iswdigit_l},
    {"iswlower_l", (uintptr_t)sym_b_iswlower_l},
    {"iswprint_l", (uintptr_t)sym_b_iswprint_l},
    {"iswpunct_l", (uintptr_t)sym_b_iswpunct_l},
    {"iswspace_l", (uintptr_t)sym_b_iswspace_l},
    {"iswupper_l", (uintptr_t)sym_b_iswupper_l},
    {"iswxdigit_l", (uintptr_t)sym_b_iswxdigit_l},
    {"kill", (uintptr_t)sym_b_kill},
    {"link", (uintptr_t)sym_b_link},
    {"listen", (uintptr_t)sym_b_listen},
    {"localeconv", (uintptr_t)sym_b_localeconv},
    {"localtime", (uintptr_t)sym_b_localtime},
    {"localtime_r", (uintptr_t)sym_b_localtime_r},
    {"log", (uintptr_t)sym_log},
    {"log10", (uintptr_t)sym_log10},
    {"longjmp", (uintptr_t)sym_b_longjmp},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"lrintf", (uintptr_t)sym_lrintf},
    {"lroundf", (uintptr_t)sym_b_lroundf},
    {"lseek", (uintptr_t)sym_b_lseek},
    {"lstat", (uintptr_t)sym_b_lstat},
    {"malloc", (uintptr_t)sym_malloc},
    {"mbrlen", (uintptr_t)sym_b_mbrlen},
    {"mbrtowc", (uintptr_t)sym_b_mbrtowc},
    {"mbsnrtowcs", (uintptr_t)sym_b_mbsnrtowcs},
    {"mbsrtowcs", (uintptr_t)sym_b_mbsrtowcs},
    {"mbtowc", (uintptr_t)sym_b_mbtowc},
    {"memalign", (uintptr_t)sym_memalign},
    {"memchr", (uintptr_t)sym_memchr},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"mkdir", (uintptr_t)sym_b_mkdir},
    {"mknod", (uintptr_t)sym_b_mknod},
    {"mmap", (uintptr_t)sym_b_mmap},
    {"modf", (uintptr_t)sym_b_modf},
    {"mprotect", (uintptr_t)sym_b_mprotect},
    {"munmap", (uintptr_t)sym_b_munmap},
    {"nanosleep", (uintptr_t)sym_b_nanosleep},
    {"newlocale", (uintptr_t)sym_b_newlocale},
    {"open", (uintptr_t)sym_b_open},
    {"openat", (uintptr_t)sym_b_openat},
    {"opendir", (uintptr_t)sym_b_opendir},
    {"openlog", (uintptr_t)sym_b_openlog},
    {"pathconf", (uintptr_t)sym_b_pathconf},
    {"perror", (uintptr_t)sym_b_perror},
    {"pipe", (uintptr_t)sym_b_pipe},
    {"poll", (uintptr_t)sym_b_poll},
    {"posix_memalign", (uintptr_t)sym_b_posix_memalign},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"printf", (uintptr_t)sym_b_printf},
    {"pthread_attr_destroy", (uintptr_t)sym_b_pthread_attr_destroy},
    {"pthread_attr_getschedparam", (uintptr_t)sym_b_pthread_attr_getschedparam},
    {"pthread_attr_getschedpolicy", (uintptr_t)sym_b_pthread_attr_getschedpolicy},
    {"pthread_attr_getstacksize", (uintptr_t)sym_b_pthread_attr_getstacksize},
    {"pthread_attr_init", (uintptr_t)sym_b_pthread_attr_init},
    {"pthread_attr_setdetachstate", (uintptr_t)sym_b_pthread_attr_setdetachstate},
    {"pthread_attr_setschedparam", (uintptr_t)sym_b_pthread_attr_setschedparam},
    {"pthread_attr_setstacksize", (uintptr_t)sym_b_pthread_attr_setstacksize},
    {"pthread_cond_broadcast", (uintptr_t)sym_b_pthread_cond_broadcast},
    {"pthread_cond_destroy", (uintptr_t)sym_b_pthread_cond_destroy},
    {"pthread_cond_init", (uintptr_t)sym_b_pthread_cond_init},
    {"pthread_cond_signal", (uintptr_t)sym_b_pthread_cond_signal},
    {"pthread_cond_timedwait", (uintptr_t)sym_b_pthread_cond_timedwait},
    {"pthread_cond_wait", (uintptr_t)sym_b_pthread_cond_wait},
    {"pthread_create", (uintptr_t)sym_b_pthread_create},
    {"pthread_detach", (uintptr_t)sym_b_pthread_detach},
    {"pthread_equal", (uintptr_t)sym_b_pthread_equal},
    {"pthread_exit", (uintptr_t)sym_b_pthread_exit},
    {"pthread_getspecific", (uintptr_t)sym_b_pthread_getspecific},
    {"pthread_join", (uintptr_t)sym_b_pthread_join},
    {"pthread_key_create", (uintptr_t)sym_b_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)sym_b_pthread_key_delete},
    {"pthread_mutex_destroy", (uintptr_t)sym_b_pthread_mutex_destroy},
    {"pthread_mutex_init", (uintptr_t)sym_b_pthread_mutex_init},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_trylock", (uintptr_t)sym_b_pthread_mutex_trylock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"pthread_mutexattr_destroy", (uintptr_t)sym_b_pthread_mutexattr_destroy},
    {"pthread_mutexattr_init", (uintptr_t)sym_b_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", (uintptr_t)sym_b_pthread_mutexattr_settype},
    {"pthread_once", (uintptr_t)sym_b_pthread_once},
    {"pthread_self", (uintptr_t)sym_b_pthread_self},
    {"pthread_setspecific", (uintptr_t)sym_b_pthread_setspecific},
    {"putc", (uintptr_t)sym_b_putc},
    {"putenv", (uintptr_t)sym_b_putenv},
    {"puts", (uintptr_t)sym_b_puts},
    {"putwc", (uintptr_t)sym_b_putwc},
    {"qsort", (uintptr_t)sym_qsort},
    {"raise", (uintptr_t)sym_b_raise},
    {"read", (uintptr_t)sym_b_read},
    {"readdir", (uintptr_t)sym_b_readdir},
    {"readlink", (uintptr_t)sym_b_readlink},
    {"realloc", (uintptr_t)sym_realloc},
    {"realpath", (uintptr_t)sym_b_realpath},
    {"recv", (uintptr_t)sym_b_recv},
    {"recvfrom", (uintptr_t)sym_b_recvfrom},
    {"remove", (uintptr_t)sym_b_remove},
    {"rename", (uintptr_t)sym_b_rename},
    {"rmdir", (uintptr_t)sym_b_rmdir},
    {"roundf", (uintptr_t)sym_b_roundf},
    {"sched_get_priority_max", (uintptr_t)sym_b_sched_get_priority_max},
    {"sched_get_priority_min", (uintptr_t)sym_b_sched_get_priority_min},
    {"sched_yield", (uintptr_t)sym_b_sched_yield},
    {"select", (uintptr_t)sym_b_select},
    {"send", (uintptr_t)sym_b_send},
    {"sendfile", (uintptr_t)sym_b_sendfile},
    {"sendto", (uintptr_t)sym_b_sendto},
    {"setbuf", (uintptr_t)sym_b_setbuf},
    {"setenv", (uintptr_t)sym_b_setenv},
    {"setjmp", (uintptr_t)sym_b_setjmp},
    {"setlocale", (uintptr_t)sym_b_setlocale},
    {"setrlimit", (uintptr_t)sym_b_setrlimit},
    {"setsockopt", (uintptr_t)sym_b_setsockopt},
    {"setvbuf", (uintptr_t)sym_b_setvbuf},
    {"shutdown", (uintptr_t)sym_b_shutdown},
    {"sigaction", (uintptr_t)sym_b_sigaction},
    {"sigemptyset", (uintptr_t)sym_b_sigemptyset},
    {"sin", (uintptr_t)sym_sin},
    {"sincos", (uintptr_t)sym_b_sincos},
    {"sincosf", (uintptr_t)sym_b_sincosf},
    {"sinf", (uintptr_t)sym_sinf},
    {"slCreateEngine", (uintptr_t)sym_b_slCreateEngine},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"socket", (uintptr_t)sym_b_socket},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"stat", (uintptr_t)sym_b_stat},
    {"statvfs", (uintptr_t)sym_b_statvfs},
    {"strcasecmp", (uintptr_t)sym_strcasecmp},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcoll", (uintptr_t)sym_strcoll},
    {"strcoll_l", (uintptr_t)sym_b_strcoll_l},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strcspn", (uintptr_t)sym_strcspn},
    {"strdup", (uintptr_t)sym_strdup},
    {"strerror", (uintptr_t)sym_b_strerror},
    {"strerror_r", (uintptr_t)sym_b_strerror_r},
    {"strftime", (uintptr_t)sym_b_strftime},
    {"strftime_l", (uintptr_t)sym_b_strftime_l},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncasecmp", (uintptr_t)sym_strncasecmp},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strncpy", (uintptr_t)sym_strncpy},
    {"strnlen", (uintptr_t)sym_strnlen},
    {"strpbrk", (uintptr_t)sym_strpbrk},
    {"strrchr", (uintptr_t)sym_strrchr},
    {"strspn", (uintptr_t)sym_strspn},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"strtof", (uintptr_t)sym_strtof},
    {"strtok", (uintptr_t)sym_strtok},
    {"strtok_r", (uintptr_t)sym_strtok_r},
    {"strtol", (uintptr_t)sym_strtol},
    {"strtold", (uintptr_t)sym_strtold},
    {"strtold_l", (uintptr_t)sym_b_strtold_l},
    {"strtoll", (uintptr_t)sym_strtoll},
    {"strtoll_l", (uintptr_t)sym_b_strtoll_l},
    {"strtoul", (uintptr_t)sym_strtoul},
    {"strtoull", (uintptr_t)sym_strtoull},
    {"strtoull_l", (uintptr_t)sym_b_strtoull_l},
    {"strxfrm", (uintptr_t)sym_strxfrm},
    {"strxfrm_l", (uintptr_t)sym_b_strxfrm_l},
    {"swprintf", (uintptr_t)sym_swprintf},
    {"symlink", (uintptr_t)sym_b_symlink},
    {"syscall", (uintptr_t)sym_b_syscall},
    {"sysconf", (uintptr_t)sym_b_sysconf},
    {"syslog", (uintptr_t)sym_b_syslog},
    {"tan", (uintptr_t)sym_tan},
    {"time", (uintptr_t)sym_b_time},
    {"towlower", (uintptr_t)sym_towlower},
    {"towlower_l", (uintptr_t)sym_b_towlower_l},
    {"towupper", (uintptr_t)sym_towupper},
    {"towupper_l", (uintptr_t)sym_b_towupper_l},
    {"truncate", (uintptr_t)sym_b_truncate},
    {"uncompress", (uintptr_t)sym_b_uncompress},
    {"ungetc", (uintptr_t)sym_b_ungetc},
    {"ungetwc", (uintptr_t)sym_b_ungetwc},
    {"unlink", (uintptr_t)sym_b_unlink},
    {"unlinkat", (uintptr_t)sym_b_unlinkat},
    {"uselocale", (uintptr_t)sym_b_uselocale},
    {"utimensat", (uintptr_t)sym_b_utimensat},
    {"vasprintf", (uintptr_t)sym_b_vasprintf},
    {"vfprintf", (uintptr_t)sym_b_vfprintf},
    {"vsnprintf", (uintptr_t)sym_b_vsnprintf},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"vsscanf", (uintptr_t)sym_vsscanf},
    {"wcrtomb", (uintptr_t)sym_b_wcrtomb},
    {"wcscoll", (uintptr_t)sym_wcscoll},
    {"wcscoll_l", (uintptr_t)sym_b_wcscoll_l},
    {"wcsftime", (uintptr_t)sym_b_wcsftime},
    {"wcslen", (uintptr_t)sym_wcslen},
    {"wcsnrtombs", (uintptr_t)sym_b_wcsnrtombs},
    {"wcsrtombs", (uintptr_t)sym_b_wcsrtombs},
    {"wcstod", (uintptr_t)sym_wcstod},
    {"wcstof", (uintptr_t)sym_wcstof},
    {"wcstol", (uintptr_t)sym_wcstol},
    {"wcstold", (uintptr_t)sym_wcstold},
    {"wcstoll", (uintptr_t)sym_wcstoll},
    {"wcstoul", (uintptr_t)sym_wcstoul},
    {"wcstoull", (uintptr_t)sym_wcstoull},
    {"wcsxfrm", (uintptr_t)sym_wcsxfrm},
    {"wcsxfrm_l", (uintptr_t)sym_b_wcsxfrm_l},
    {"wctob", (uintptr_t)sym_b_wctob},
    {"wctype", (uintptr_t)sym_wctype},
    {"wmemchr", (uintptr_t)sym_wmemchr},
    {"wmemcmp", (uintptr_t)sym_wmemcmp},
    {"wmemcpy", (uintptr_t)sym_wmemcpy},
    {"wmemmove", (uintptr_t)sym_wmemmove},
    {"wmemset", (uintptr_t)sym_wmemset},
    {"write", (uintptr_t)sym_b_write},
    {"writev", (uintptr_t)sym_b_writev},
    {"zError", (uintptr_t)sym_b_zError},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
