/* pvz_button_icons.h -- generated by tools/make_button_icons.py: where each
 * button is in resources/buttons/icons.png. The character of button i is
 * U+E000 + i. */
#define PVZ_ICON_H 96
#define PVZ_ICON_COUNT 13
enum {
  PVZ_ICON_A,
  PVZ_ICON_B,
  PVZ_ICON_X,
  PVZ_ICON_Y,
  PVZ_ICON_PLUS,
  PVZ_ICON_MINUS,
  PVZ_ICON_L,
  PVZ_ICON_R,
  PVZ_ICON_ZL,
  PVZ_ICON_ZR,
  PVZ_ICON_LSTICK,
  PVZ_ICON_RSTICK,
  PVZ_ICON_DPAD,
};
static const struct {
  int x, w;
} k_pvz_icons[PVZ_ICON_COUNT] = {
    {0, 96}, /* A */
    {96, 96}, /* B */
    {192, 96}, /* X */
    {288, 96}, /* Y */
    {384, 96}, /* PLUS */
    {480, 96}, /* MINUS */
    {576, 120}, /* L */
    {696, 120}, /* R */
    {816, 139}, /* ZL */
    {955, 139}, /* ZR */
    {1094, 96}, /* LSTICK */
    {1190, 96}, /* RSTICK */
    {1286, 96}, /* DPAD */
};
